// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;

namespace Nhom6_TestCase_Dangnhap_Muahang
{
    [TestFixture]
    public class NhaSanXuatTest
    {
        private IWebDriver driver;
        public IDictionary<string, object> vars { get; private set; }
        private IJavaScriptExecutor js;
        [SetUp]
        public void SetUp()
        {
            driver = new ChromeDriver();
            js = (IJavaScriptExecutor)driver;
            vars = new Dictionary<string, object>();
        }
        [TearDown]
        protected void TearDown()
        {
            driver.Quit();
        }
        [Test]
        public void tCQLNhaSX02()
        {
            driver.Navigate().GoToUrl("http://webbannon.somee.com/Admin_QLNSX/QuanLyNhaSanXuat_Them");
            driver.Manage().Window.Size = new System.Drawing.Size(1366, 726);
            driver.FindElement(By.Id("TenNhaSanXuat_T")).Click();
            driver.FindElement(By.Id("TenNhaSanXuat_T")).Click();
            driver.FindElement(By.Id("TenNhaSanXuat_T")).SendKeys("mỹ");
            driver.FindElement(By.Id("TenNhaSanXuat_T")).Click();
            driver.FindElement(By.CssSelector("form > .btn")).Click();
            Assert.That(driver.FindElement(By.CssSelector("form")).Text, Is.EqualTo("Không thêm nước sản xuất"));
            driver.Close();
        }
        [Test]
        public void tCQLNhaSX03()
        {
            driver.Navigate().GoToUrl("http://webbannon.somee.com/Admin_QLNSX/QuanLyNhaSanXuat_Them");
            driver.Manage().Window.Size = new System.Drawing.Size(1366, 726);
            driver.FindElement(By.Id("TenNhaSanXuat_T")).Click();
            driver.FindElement(By.Id("NuocSanXuat_T")).Click();
            driver.FindElement(By.Id("NuocSanXuat_T")).SendKeys("Ý");
            driver.FindElement(By.CssSelector(".container-fluid:nth-child(2)")).Click();
            driver.FindElement(By.CssSelector("form > .btn")).Click();
            Assert.That(driver.FindElement(By.CssSelector(".card-body")).Text, Is.EqualTo("Tên Nhà Sản Xuất Không Được Bỏ Trống"));
            driver.Close();
        }
        [Test]
        public void tCQLNhaSX04()
        {
            driver.Navigate().GoToUrl("http://webbannon.somee.com/Admin_QLNSX/QuanLyNhaSanXuat_Them");
            driver.Manage().Window.Size = new System.Drawing.Size(1366, 728);
            driver.FindElement(By.Id("TenNhaSanXuat_T")).Click();
            driver.FindElement(By.Id("TenNhaSanXuat_T")).SendKeys("DB");
            driver.FindElement(By.Id("NuocSanXuat_T")).Click();
            driver.FindElement(By.Id("NuocSanXuat_T")).SendKeys("DB");
            driver.FindElement(By.CssSelector("form > .btn")).Click();
            Assert.That(driver.FindElement(By.CssSelector(".container-fluid:nth-child(2)")).Text, Is.EqualTo("Thông Tin Nhà Sản Xuất\\\\nTrở Về\\\\n( THÊM NHÀ SẢN XUẤT THÀNH CÔNG )\\\\nTên Nhà Sản Xuất\\\\nNước Sản Xuất\\\\nThêm"));
            driver.Close();
        }
        [Test]
        public void tCQLNhaSX05()
        {
            driver.Navigate().GoToUrl("http://webbannon.somee.com/Admin_QLNSX/QuanLyNhaSanXuat_Them");
            driver.Manage().Window.Size = new System.Drawing.Size(1366, 726);
            driver.FindElement(By.Id("TenNhaSanXuat_T")).Click();
            driver.FindElement(By.Id("TenNhaSanXuat_T")).SendKeys("nho");
            driver.FindElement(By.Id("NuocSanXuat_T")).Click();
            driver.FindElement(By.Id("NuocSanXuat_T")).SendKeys("nho");
            driver.FindElement(By.CssSelector("form > .btn")).Click();
            driver.Close();
        }
        [Test]
        public void tCQLNhaSX06()
        {
            driver.Navigate().GoToUrl("http://webbannon.somee.com/Admin_QLNSX/QuanLyNhaSanXuat_Them");
            driver.Manage().Window.Size = new System.Drawing.Size(1366, 728);
            driver.FindElement(By.Id("TenNhaSanXuat_T")).Click();
            driver.FindElement(By.Id("TenNhaSanXuat_T")).SendKeys("MUP");
            driver.FindElement(By.Id("TenNhaSanXuat_T")).Click();
            driver.FindElement(By.Id("TenNhaSanXuat_T")).SendKeys("Mup");
            driver.FindElement(By.Id("NuocSanXuat_T")).Click();
            driver.FindElement(By.Id("NuocSanXuat_T")).Click();
            driver.FindElement(By.Id("NuocSanXuat_T")).SendKeys("chu");
            driver.FindElement(By.CssSelector("form > .btn")).Click();
            Assert.That(driver.FindElement(By.CssSelector("form")).Text, Is.EqualTo("Tên Nhà Sản Xuất\\\\nNước Sản Xuất\\\\nThêm"));
            driver.Close();
        }
        [Test]
        public void tCQLNhaSX07()
        {
            driver.Navigate().GoToUrl("http://webbannon.somee.com/Admin_QLNSX/QuanLyNhaSanXuat_Them");
            driver.Manage().Window.Size = new System.Drawing.Size(1366, 728);
            driver.FindElement(By.Id("TenNhaSanXuat_T")).Click();
            driver.FindElement(By.Id("TenNhaSanXuat_T")).SendKeys("DB");
            driver.FindElement(By.CssSelector(".container-fluid:nth-child(2)")).Click();
            driver.FindElement(By.Id("NuocSanXuat_T")).Click();
            driver.FindElement(By.Id("NuocSanXuat_T")).SendKeys("ui");
            driver.FindElement(By.CssSelector("form > .btn")).Click();
            Assert.That(driver.FindElement(By.CssSelector(".card-body")).Text, Is.EqualTo("( THÊM NHÀ SẢN XUẤT THÀNH CÔNG )\\\\nTên Nhà Sản Xuất\\\\nNước Sản Xuất\\\\nThêm"));
            driver.Close();
        }
        [Test]
        public void tCQLNhaSX08()
        {
            driver.Navigate().GoToUrl("http://webbannon.somee.com/Admin_QLNSX/QuanLyNhaSanXuat_Them");
            driver.Manage().Window.Size = new System.Drawing.Size(1366, 726);
            driver.FindElement(By.Id("TenNhaSanXuat_T")).Click();
            driver.FindElement(By.Id("TenNhaSanXuat_T")).Click();
            driver.FindElement(By.Id("TenNhaSanXuat_T")).SendKeys("Dhji");
            driver.FindElement(By.Id("NuocSanXuat_T")).Click();
            driver.FindElement(By.Id("NuocSanXuat_T")).SendKeys("nho");
            driver.FindElement(By.CssSelector("form > .btn")).Click();
            Assert.That(driver.FindElement(By.CssSelector("form")).Text, Is.EqualTo("Tên Nhà Sản Xuất\\\\nNước Sản Xuất\\\\nThêm"));
            driver.Close();
        }
    }
}

