// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;

namespace Nhom6_TestCase_Dangnhap_Muahang
{
    [TestFixture]
    public class TCQLNhaSX01Test
    {
        private IWebDriver driver;
        public IDictionary<string, object> vars { get; private set; }
        private IJavaScriptExecutor js;
        [SetUp]
        public void SetUp()
        {
            driver = new ChromeDriver();
            js = (IJavaScriptExecutor)driver;
            vars = new Dictionary<string, object>();
        }
        [TearDown]
        protected void TearDown()
        {
            driver.Quit();
        }
        [Test]
        public void tCQLNhaSX01()
        {
            driver.Navigate().GoToUrl("http://webbannon.somee.com/DangNhap/DangNhap");
            driver.Manage().Window.Size = new System.Drawing.Size(1050, 708);
            driver.FindElement(By.Id("TenDangNhap")).Click();
            driver.FindElement(By.Id("TenDangNhap")).SendKeys("heotranthanh");
            driver.FindElement(By.Id("MatKhau")).Click();
            driver.FindElement(By.Id("MatKhau")).SendKeys("Heo@0905963271");
            driver.FindElement(By.Name("sbdangnhap")).Click();
            driver.Navigate().GoToUrl("http://webbannon.somee.com/Admin_QLNSX/QuanLyNhaSanXuat_Them");
            driver.FindElement(By.Id("TenNhaSanXuat_T")).Click();
            driver.FindElement(By.Id("TenNhaSanXuat_T")).SendKeys("");
            driver.FindElement(By.Id("NuocSanXuat_T")).Click();
            driver.FindElement(By.Id("NuocSanXuat_T")).SendKeys("db");
            driver.FindElement(By.XPath("//*[@id='content-wrapper']/div/div/div/div/form/button")).Click();
            Assert.That(driver.FindElement(By.XPath("//*[@id='content-wrapper']/div/div/div/div/form/div/div[1]/label")).Text, Is.EqualTo("Tên Nhà Sản Xuất ( Tên Nhà Sản Xuất Không Được Bỏ Trống )"));
        }

        [Test]
        public void tCQLNhaSX02()
        {
            driver.Navigate().GoToUrl("http://webbannon.somee.com/DangNhap/DangNhap");
            driver.Manage().Window.Size = new System.Drawing.Size(1050, 708);
            driver.FindElement(By.Id("TenDangNhap")).Click();
            driver.FindElement(By.Id("TenDangNhap")).SendKeys("heotranthanh");
            driver.FindElement(By.Id("MatKhau")).Click();
            driver.FindElement(By.Id("MatKhau")).SendKeys("Heo@0905963271");
            driver.FindElement(By.Name("sbdangnhap")).Click();
            driver.Navigate().GoToUrl("http://webbannon.somee.com/Admin_QLNSX/QuanLyNhaSanXuat_Them");
            driver.FindElement(By.Id("TenNhaSanXuat_T")).Click();
            driver.FindElement(By.Id("TenNhaSanXuat_T")).SendKeys("mỹ");
            driver.FindElement(By.Id("NuocSanXuat_T")).Click();
            driver.FindElement(By.Id("NuocSanXuat_T")).SendKeys("");
            driver.FindElement(By.XPath("//*[@id='content-wrapper']/div/div/div/div/form/button")).Click();
            Assert.That(driver.FindElement(By.XPath("//*[@id='content-wrapper']/div/div/div/div/form/div/div[2]/label")).Text, Is.EqualTo("Nước Sản Xuất ( Nước Sản Xuất Không Được Bỏ Trống )"));
        }

        [Test]
        public void tCQLNhaSX03()
        {
            driver.Navigate().GoToUrl("http://webbannon.somee.com/DangNhap/DangNhap");
            driver.Manage().Window.Size = new System.Drawing.Size(1050, 708);
            driver.FindElement(By.Id("TenDangNhap")).Click();
            driver.FindElement(By.Id("TenDangNhap")).SendKeys("heotranthanh");
            driver.FindElement(By.Id("MatKhau")).Click();
            driver.FindElement(By.Id("MatKhau")).SendKeys("Heo@0905963271");
            driver.FindElement(By.Name("sbdangnhap")).Click();
            driver.Navigate().GoToUrl("http://webbannon.somee.com/Admin_QLNSX/QuanLyNhaSanXuat_Them");
            driver.FindElement(By.Id("TenNhaSanXuat_T")).Click();
            driver.FindElement(By.Id("TenNhaSanXuat_T")).SendKeys("mỹ");
            driver.FindElement(By.Id("NuocSanXuat_T")).Click();
            driver.FindElement(By.Id("NuocSanXuat_T")).SendKeys("my");
            driver.FindElement(By.XPath("//*[@id='content-wrapper']/div/div/div/div/form/button")).Click();
            Assert.That(driver.FindElement(By.XPath("//*[@id='content-wrapper']/div/div/div/div/h4")).Text, Is.EqualTo("( THÊM NHÀ SẢN XUẤT THÀNH CÔNG )"));
        }

    }
}

