// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
namespace Nhom6_TestCase_Dangnhap_Muahang
{
    [TestFixture]
    public class SuaNhaSanXuatTest
    {
        private IWebDriver driver;
        public IDictionary<string, object> vars { get; private set; }
        private IJavaScriptExecutor js;
        [SetUp]
        public void SetUp()
        {
            driver = new ChromeDriver();
            js = (IJavaScriptExecutor)driver;
            vars = new Dictionary<string, object>();
        }
        [TearDown]
        protected void TearDown()
        {
            driver.Quit();
        }
        [Test]
        public void TC_SuaNhaSanXuat_01()
        {
            driver.Navigate().GoToUrl("http://webbannon.somee.com/DangNhap/DangNhap");
            driver.Manage().Window.Size = new System.Drawing.Size(1103, 621);
            js.ExecuteScript("window.scrollTo(0,116)");
            driver.FindElement(By.Id("TenDangNhap")).Click();
            driver.FindElement(By.Id("TenDangNhap")).SendKeys("heotranthanh");
            driver.FindElement(By.Id("MatKhau")).Click();
            driver.FindElement(By.Id("MatKhau")).SendKeys("Heo@0905963271");
            driver.FindElement(By.Name("sbdangnhap")).Click();
            driver.Navigate().GoToUrl("http://webbannon.somee.com/Admin_QLNSX/QuanLyNhaSanXuat");
            driver.FindElement(By.CssSelector(".odd:nth-child(1) .icon_tacvu > .fas")).Click();
            driver.FindElement(By.CssSelector(".form-group:nth-child(1)")).Click();
            driver.FindElement(By.Id("TenNhaSanXuat_T")).Clear();
            driver.FindElement(By.Id("TenNhaSanXuat_T")).SendKeys("Test123");
            driver.FindElement(By.Id("NuocSanXuat_T")).Click();
            driver.FindElement(By.Id("NuocSanXuat_T")).Clear();
            driver.FindElement(By.Id("NuocSanXuat_T")).SendKeys("Test123");
            driver.FindElement(By.CssSelector("form > .btn")).Click();
            driver.FindElement(By.CssSelector(".mt-3 > .mb-2")).Click();
            Assert.That(driver.FindElement(By.CssSelector(".mt-3 > .mb-2")).Text, Is.EqualTo("(CẬP NHẬT NHÀ SẢN XUẤT THÀNH CÔNG )"));
            driver.Close();
        }


        [Test]
        public void TC_SuaNhaSanXuat_02()
        {
            driver.Navigate().GoToUrl("http://webbannon.somee.com/DangNhap/DangNhap");
            driver.Manage().Window.Size = new System.Drawing.Size(1103, 621);
            driver.FindElement(By.Id("TenDangNhap")).Click();
            driver.FindElement(By.Id("TenDangNhap")).SendKeys("heotranthanh");
            driver.FindElement(By.Id("MatKhau")).Click();
            driver.FindElement(By.Id("MatKhau")).SendKeys("Heo@0905963271");
            driver.FindElement(By.Name("sbdangnhap")).Click();
            driver.Navigate().GoToUrl("http://webbannon.somee.com/Admin_QLNSX/QuanLyNhaSanXuat");
            driver.FindElement(By.CssSelector(".odd:nth-child(1) .icon_tacvu > .fas")).Click();
            driver.FindElement(By.CssSelector(".form-row")).Click();
            driver.FindElement(By.Id("TenNhaSanXuat_T")).Clear();
            driver.FindElement(By.Id("TenNhaSanXuat_T")).SendKeys("Test");
            driver.FindElement(By.Id("NuocSanXuat_T")).Clear();
            driver.FindElement(By.CssSelector("form > .btn")).Click();
            driver.FindElement(By.CssSelector(".form-group:nth-child(2)")).Click();
            Thread.Sleep(4000);
            IWebElement thongbao = driver.FindElement(By.XPath("//*[@id='content-wrapper']/div/div/div/div/form/div/div[2]/label"));
            Assert.That(thongbao.Text, Is.EqualTo("Nước Sản Xuất ( Nước Sản Xuất Không Được Bỏ Trống )"));
            driver.Close();
        }
        [Test]
        public void TC_SuaNhaSanXuat_03()
        {
            driver.Navigate().GoToUrl("http://webbannon.somee.com/DangNhap/DangNhap");
            driver.Manage().Window.Size = new System.Drawing.Size(1103, 621);
            driver.FindElement(By.Id("TenDangNhap")).Click();
            driver.FindElement(By.Id("TenDangNhap")).SendKeys("heotranthanh");
            driver.FindElement(By.Id("MatKhau")).Click();
            driver.FindElement(By.Id("MatKhau")).SendKeys("Heo@0905963271");
            driver.FindElement(By.Name("sbdangnhap")).Click();
            driver.Navigate().GoToUrl("http://webbannon.somee.com/Admin_QLNSX/QuanLyNhaSanXuat");
            driver.FindElement(By.CssSelector(".odd:nth-child(1) .icon_tacvu > .fas")).Click();
            driver.FindElement(By.CssSelector(".form-row")).Click();
            driver.FindElement(By.Id("TenNhaSanXuat_T")).Clear();
            driver.FindElement(By.Id("NuocSanXuat_T")).Clear();
            driver.FindElement(By.Id("NuocSanXuat_T")).SendKeys("Test");
            driver.FindElement(By.CssSelector("form > .btn")).Click();
            driver.FindElement(By.CssSelector(".form-group:nth-child(2)")).Click();
            Thread.Sleep(4000);
            IWebElement thongbao = driver.FindElement(By.XPath("//*[@id='content-wrapper']/div/div/div/div/form/div/div[1]/label"));
            Assert.That(thongbao.Text, Is.EqualTo("Tên Nhà Sản Xuất ( Tên Nhà Sản Xuất Không Được Bỏ Trống )"));
            driver.Close();
        }
    }
}

