// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;

namespace Nhom6_TestCase_Dangnhap_Muahang
{
    [TestFixture]
    public class TCQLtimkiemND08Test
    {
        private IWebDriver driver;
        public IDictionary<string, object> vars { get; private set; }
        private IJavaScriptExecutor js;
        [SetUp]
        public void SetUp()
        {
            driver = new ChromeDriver();
            js = (IJavaScriptExecutor)driver;
            vars = new Dictionary<string, object>();
        }
        [TearDown]
        protected void TearDown()
        {
            //driver.Quit();
        }

        [Test]
        public void tCQLtimkiemND01()
        {
            driver.Navigate().GoToUrl("http://webbannon.somee.com/DangNhap/DangNhap");
            driver.Manage().Window.Size = new System.Drawing.Size(695, 728);
            driver.FindElement(By.Id("TenDangNhap")).Click();
            driver.FindElement(By.Id("TenDangNhap")).SendKeys("heotranthanh");
            driver.FindElement(By.Id("MatKhau")).Click();
            driver.FindElement(By.Id("MatKhau")).SendKeys("Heo@0905963271");
            driver.FindElement(By.Name("sbdangnhap")).Click();
            driver.Navigate().GoToUrl("http://webbannon.somee.com/Admin/QuanLyNguoiDung");
            driver.FindElement(By.CssSelector("#dataTable_filter .form-control")).SendKeys("nam");
            driver.FindElement(By.Id("dataTable_info")).Click();
            driver.FindElement(By.Id("dataTable_info")).Click();
            Assert.That(driver.FindElement(By.Id("dataTable_info")).Text, Is.EqualTo("Từ Hàng 1 Đến Hàng 4 Trong Số 4 Hàng (Tìm Thấy Trong Tổng Số 15 Hàng)"));
        }


    }
}

