// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
namespace Nhom6_TestCase_Dangnhap_Muahang
{
    [TestFixture]
    public class TimKiemTest
    {
        private IWebDriver driver;
        public IDictionary<string, object> vars { get; private set; }
        private IJavaScriptExecutor js;
        [SetUp]
        public void SetUp()
        {
            driver = new ChromeDriver();
            js = (IJavaScriptExecutor)driver;
            vars = new Dictionary<string, object>();
        }
        [TearDown]
        protected void TearDown()
        {
            driver.Quit();
        }
        [Test]
        public void tCQLtimkiemND01()
        {
            driver.Navigate().GoToUrl("http://webbannon.somee.com/Admin/QuanLyNguoiDung");
            driver.Manage().Window.Size = new System.Drawing.Size(1366, 728);
            driver.FindElement(By.CssSelector("#dataTable_filter .form-control")).Click();
            driver.FindElement(By.Id("dataTable_filter")).Click();
            driver.Close();
        }
        [Test]
        public void tCQLtimkiemND02()
        {
            driver.Navigate().GoToUrl("http://webbannon.somee.com/Admin/QuanLyNguoiDung");
            driver.Manage().Window.Size = new System.Drawing.Size(1366, 728);
            driver.FindElement(By.CssSelector("#dataTable_filter .form-control")).Click();
            driver.FindElement(By.CssSelector("#dataTable_filter .form-control")).SendKeys("nam");
            Assert.That(driver.FindElement(By.Id("dataTable_filter")).Text, Is.EqualTo("Tìm Kiếm :"));
            driver.Close();
        }
        [Test]
        public void tCQLtimkiemND03()
        {
            driver.Navigate().GoToUrl("http://webbannon.somee.com/Admin/QuanLyNguoiDung");
            driver.Manage().Window.Size = new System.Drawing.Size(1366, 728);
            driver.FindElement(By.CssSelector("#dataTable_filter .form-control")).Click();
            driver.FindElement(By.CssSelector("#dataTable_filter .form-control")).SendKeys("nữ");
            Assert.That(driver.FindElement(By.Id("dataTable_filter")).Text, Is.EqualTo("Tìm Kiếm :"));
            driver.Close();
        }
        [Test]
        public void tCQLtimkiemND04()
        {
            driver.Navigate().GoToUrl("http://webbannon.somee.com/Admin/QuanLyNguoiDung");
            driver.Manage().Window.Size = new System.Drawing.Size(1366, 728);
            driver.FindElement(By.CssSelector("#dataTable_filter .form-control")).Click();
            driver.FindElement(By.CssSelector("#dataTable_filter .form-control")).SendKeys("1");
            Assert.That(driver.FindElement(By.Id("dataTable_filter")).Text, Is.EqualTo("Tìm Kiếm :"));
            driver.Close();
        }
        [Test]
        public void tCQLtimkiemND05()
        {
            driver.Navigate().GoToUrl("http://webbannon.somee.com/Admin/QuanLyNguoiDung");
            driver.Manage().Window.Size = new System.Drawing.Size(1366, 728);
            driver.FindElement(By.CssSelector("#dataTable_filter .form-control")).Click();
            driver.FindElement(By.CssSelector("#dataTable_filter .form-control")).SendKeys("5/27/2020");
            Assert.That(driver.FindElement(By.Id("dataTable_filter")).Text, Is.EqualTo("Tìm Kiếm :"));
            driver.Close();
        }
        [Test]
        public void tCQLtimkiemND06()
        {
            driver.Navigate().GoToUrl("http://webbannon.somee.com/Admin/QuanLyNguoiDung");
            driver.Manage().Window.Size = new System.Drawing.Size(1366, 728);
            driver.FindElement(By.CssSelector("#dataTable_filter .form-control")).Click();
            driver.FindElement(By.CssSelector("#dataTable_filter .form-control")).SendKeys("1/1/1999");
            Assert.That(driver.FindElement(By.CssSelector("tfoot th:nth-child(8)")).Text, Is.EqualTo("Email"));
            driver.Close();
        }
        [Test]
        public void tCQLtimkiemND07()
        {
            driver.Navigate().GoToUrl("http://webbannon.somee.com/Admin/QuanLyNguoiDung");
            driver.Manage().Window.Size = new System.Drawing.Size(1366, 726);
            driver.FindElement(By.CssSelector("#dataTable_filter .form-control")).Click();
            driver.FindElement(By.CssSelector("#dataTable_filter .form-control")).SendKeys("huongdb@gmail.com");
            Assert.That(driver.FindElement(By.Id("dataTable_filter")).Text, Is.EqualTo("Tìm Kiếm :"));
            driver.Close();
        }
        [Test]
        public void tCQLtimkiemND08()
        {
            driver.Navigate().GoToUrl("http://webbannon.somee.com/Admin/QuanLyNguoiDung");
            driver.Manage().Window.Size = new System.Drawing.Size(1366, 726);
            driver.FindElement(By.CssSelector("#dataTable_filter .form-control")).Click();
            driver.FindElement(By.CssSelector("#dataTable_filter .form-control")).SendKeys("dsd");
            Assert.That(driver.FindElement(By.Id("dataTable_filter")).Text, Is.EqualTo("Tìm Kiếm :"));
            driver.Close();
        }
        [Test]
        public void tCQLtimkiemND09()
        {
            driver.Navigate().GoToUrl("http://webbannon.somee.com/Admin/QuanLyNguoiDung");
            driver.Manage().Window.Size = new System.Drawing.Size(1366, 726);
            driver.FindElement(By.CssSelector("#dataTable_filter .form-control")).Click();
            driver.FindElement(By.CssSelector("#dataTable_filter .form-control")).SendKeys("admin");
            Assert.That(driver.FindElement(By.CssSelector(".table-responsive")).Text, Is.EqualTo("Thêm\\\\nChọn Số Dòng Sẽ Hiển Thị Trên 1 Trang\\\\n10\\\\n25\\\\n50\\\\n100\\\\nTìm Kiếm :\\\\nTên Đăng Nhập Mật Khẩu Quyền Hạn Tên Khách Hàng Ngày Sinh Số Điện Thoại Địa Chỉ Email\\\\nTên Đăng Nhập Mật Khẩu Quyền Hạn Tên Khách Hàng Ngày Sinh Số Điện Thoại Địa Chỉ Email\\\\nadmin 251800DA8D338EB82819105D5F3C7629 2 dsdsad 5/27/2020 0982738239 sdsdsd huongdb@gmail.com\\\\nAdminNam 21837B5110B12B12312EB994F0DEB439 2 Nam Admin 8/2/1996 1 0773654033 frfrf npn0299123@gmail.com\\\\nTừ Hàng 1 Đến Hàng 2 Trong Số 2 Hàng (Tìm Thấy Trong Tổng Số 14 Hàng)\\\\nTrước\\\\n1\\\\nSau"));
            driver.Close();
        }
    }
}

